version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./client.Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
  server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    restart: always
    environment:
      APP_ENV: production
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: one_poll
      SESSION_SECRET: secret
      ADDR: :3000
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: one_poll
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /etc/one-poll/mariadb/data:/var/lib/mysql

