version: "3"
services:
  server:
    build:
      context: ../server/
      dockerfile: ../dev/server.Dockerfile
    restart: always
    volumes:
      - ../server:/go/src/github.com/mazrean/one-poll
    environment:
      APP_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: one_poll
      SESSION_SECRET: secret
      ADDR: :3000
    ports: 
      - 3000:3000
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: one_poll
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ../mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=pass
    links:
      - mariadb
    ports:
      - 8000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

