version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    restart: unless-stopped
    environment:
      DB_MIGRATE: "true"
      APP_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_HOSTNAME: tidb
      DB_PORT: 4000
      DB_DATABASE: one_poll
      SESSION_SECRET: secret
      ADDR: :3000
    ports:
      - 3000:3000
    depends_on:
      tidb:
        condition: service_started
      database_init:
        condition: service_completed_successfully
  tidb:
    build:
      context: .
      dockerfile: ./tidb.Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
      - 2379:2379
    command: ["--tiflash", "0", "--kv.config", "/tikv/config.toml"]
    volumes:
      - ./tidb/tikv.toml:/tikv/config.toml:ro
      - ../tidb/tikv/data:/tikv/data
  database_init:
    image: mysql:8.4.2
    restart: on-failure
    command: mysql -htidb -uroot -P4000 -e "CREATE DATABASE IF NOT EXISTS one_poll;"
    depends_on:
      - tidb
