services:
  one-poll-client:
    image: ghcr.io/mazrean/one-poll-client:latest
    container_name: one-poll-client
    restart: always
    expose:
      - "8080"
    networks:
      - default
      - caddy-network
  one-poll-server:
    image: ghcr.io/mazrean/one-poll-server:latest
    container_name: one-poll-server
    restart: always
    environment:
      APP_ENV: production
      DB_USERNAME: one_poll
      DB_PASSWORD:
      DB_HOSTNAME: one-poll-mariadb
      DB_PORT: 3306
      DB_DATABASE: one_poll
      SESSION_SECRET:
      ADDR: :3000
      RP_ID: one-poll.mazrean.com
      RP_ORIGIN: https://one-poll.mazrean.com
      RP_NAME: One Poll
    depends_on:
      one-poll-mariadb:
        condition: service_healthy
  one-poll-mariadb:
    image: mariadb:10.5.2
    container_name: one-poll-mariadb
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_USER: one_poll
      MYSQL_DATABASE: one_poll
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /etc/one-poll/mariadb/data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ppass"]
      timeout: 5m
      interval: 1s
      retries: 1000
networks:
  caddy-network:
    name: caddy-network
    external: true
