name: Client CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  NODE_VERSION: '18'

jobs:
  packages:
    name: Client Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
  genApi:
    name: Generate APIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
      - run: npm run gen-api
        working-directory: ./client
      - uses: actions/upload-artifact@v4
        with:
          name: apis
          path: ./client/src/lib/apis/generated
  build:
    name: Client Build
    runs-on: ubuntu-latest
    needs: [packages, genApi]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
      - uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./client/src/lib/apis/generated
      - run: npm run build
        env:
          NODE_ENV: production
        working-directory: ./client
  lint:
    name: Client Lint
    runs-on: ubuntu-latest
    needs: [packages, genApi]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
      - uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./client/src/lib/apis/generated
      - run: npm run lint -- --max-warnings=0
        working-directory: ./client
  typeCheck:
    name: Client Type Check
    runs-on: ubuntu-latest
    needs: [packages, genApi]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: ./client
      - uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./client/src/lib/apis/generated
      - run: npm run type-check
        working-directory: ./client
