name: Go Dependency Submission
on:
  push:
    branches:
      - main
      - dev/dependency_submission

permissions:
  contents: write

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./server/go.mod
      - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
            go-mod-path: ./server/go.mod
